### ISSUE TITLE
Question: How to reproduce UBW-C on CIFAR10 correctly?

### ISSUE THREAD

**Issue by gongzhimin** [THUYimingLi/Untargeted_Backdoor_Watermark#1] opened 2022-11-20 06:26 UTC
Hello, authors. Thank you for sharing the code for the great paper!
And I have some questions when reproducing the result on CIFAR10.
I keep hyper-parameters in `UBW_C.py` as follows:
```python
SOURCE_CLASS = 0
TARGET_CLASS = 1
POISON_NUM = 5000   # namely, the poison rate is 10%
CRAFT_ITERS = 250
RETRAIN_ITERS = 50
TRAIN_EPOCHS = 40
EPS = 16. / 255
DATASET = 'CIFAR10'
PATCH_SIZE = 8
IMAGE_SIZE = 32
CLASS_NUM = 10
BETA = 2.0
````
and calculate ASR of the poisoned model 'ResNet18_CIFAR10_dis_2.0_5000_8_10_0_1.pth' with `eval_ASR.py`.
But I get `poison asr = 0.7437` and `full poison asr = 0.4454`, which is lower than ASR-A=89.80% and ASR-C=87.56% reported in the paper.
![image](https://user-images.githubusercontent.com/50874957/202888823-1fda6675-20a1-4ff8-ada1-be77ddf57cf8.png)
I don't know why, because I didn't change the code in other places. Would you provide more information about reproducing? Looking forward to your advice.

**Comment by THUYimingLi** [comment] 2022-11-20 18:08
> Hello, authors. Thank you for sharing the code for the great paper! And I have some questions when reproducing the result on CIFAR10. I keep hyper-parameters in `UBW_C.py` as follows:
> 
> ```python
> SOURCE_CLASS = 0
> TARGET_CLASS = 1
> POISON_NUM = 5000   # namely, the poison rate is 10%
> CRAFT_ITERS = 250
> RETRAIN_ITERS = 50
> TRAIN_EPOCHS = 40
> EPS = 16. / 255
> DATASET = 'CIFAR10'
> PATCH_SIZE = 8
> IMAGE_SIZE = 32
> CLASS_NUM = 10
> BETA = 2.0
> ```
> 
> and calculate ASR of the poisoned model 'ResNet18_CIFAR10_dis_2.0_5000_8_10_0_1.pth' with `eval_ASR.py`. But I get `poison asr = 0.7437` and `full poison asr = 0.4454`, which is lower than ASR-A=89.80% and ASR-C=87.56% reported in the paper. ![image](https://user-images.githubusercontent.com/50874957/202888823-1fda6675-20a1-4ff8-ada1-be77ddf57cf8.png) I don't know why, because I didn't change the code in other places. Would you provide more information about reproducing? Looking forward to your advice.

Hi, thank you for your interest in our work! Firstly, I have to apologize that I haven't finished the update and review of the codes, due to some personal issues such as job hunting. I will update the repo before the end of this month ASAP. I will let you know when I reproduce your results or know what happens.

**Comment by gongzhimin** [comment] 2022-11-21 02:27
Thank you for the reply! Wish you all the best.

**Comment by Suhina123** [comment] 2023-11-01 19:59
Hello, 

Is the code updated?
Thank you:)

**Comment by THUYimingLi** [comment] 2023-11-02 01:15
Sorry for my late response. We have run the codes on our local servers, and the results are normal and reproducible. Note that the std of running UBW-C is relatively large (similar to all bi-level-based methods), as mentioned in our appendix. You may need to run more times and average them to get the correct results :)

**Comment by THUYimingLi** [comment] 2023-11-02 01:17
I will keep this issue open for a few days. I will close it if you don't have further questions.

**Closed as completed** 2023-12-19 02:55 UTC
